### ISSUE TITLE
ms createuser

### ISSUE THREAD

**Issue by pfrybar** [ModelSEED/ModelSEED#11]
Running the 'ms createuser' command creates a bad password in the .modelseed config file. Trying to login as the user will then fail because of an 'invalid password'.

I believe this has to do with the crypting of the password in createuser.pm. It's using a salt of 1, should use a random string of length 2. Should be a pretty simple fix.

This brings up an important question regarding whether we want to allow users in our system who do not exist the SEED.

**Comment by devoid** [comment]
Fixed with 8d49834691bc8caab5b64bb496fb456b94d19a7d ?

**Comment by pfrybar** [comment]
Yep, my bad, forgot to comment and close issue.

**Comment by cshenry** [comment]
Btw, regarding whether we want to allow creation of nonseed accounts, I
think we do. We donot control the seed account system, and I don't want to
fight with that when we want to get things done. For example, I needed to
make a kbase account to be able to look at and test kbase data from the
model seed, but I doubt gordon would have agreed to set up a kbase account
for us. Ultimately, I think we should link this code to a web server that
tracks the email and login of accounts created for the sake of keeping use
statistics, but for now, the current functionality is fine.
Chris
