### ISSUE TITLE
Master Failing Tests

### ISSUE THREAD

**Issue by devoid** [ModelSEED/ModelSEED#125]
See recent tests:
https://travis-ci.org/#!/ModelSEED/ModelSEED/jobs/2845742

```
Global symbol "$mergeto" requires explicit package name at /home/travis/builds/ModelSEED/ModelSEED/blib/lib/ModelSEED/MS/Biochemistry.pm line 389.
```

**Comment by samseaver** [comment]
That's the thing, I didn't push to master, shouldn't a merge of a pull-request have brought this up?

**Comment by devoid** [comment]
It looks like Chris did a manual merge-conflict and didn't define some variables. Since they're being accessed without being defined, and there are no comments, I have no idea how to proceed. @cshenry ?

**Comment by cshenry** [comment]
I was rushed in the merge, because I was trying to process it before the massive refactors of the code got too out of control. Not sure how I recommend handling these massive refactors with respect to the pull requests in the future.

Anyhow, this is fixed now.
