### ISSUE TITLE
Failed require ModelSEED::MS::GapgenFormulation

### ISSUE THREAD

**Issue by devoid** [ModelSEED/ModelSEED#13]
```
#   Failed test 'require ModelSEED::MS::GapgenFormulation;'
#   at t/require.t line 14.
#     Tried to require 'ModelSEED::MS::GapgenFormulation'.
#     Error:  Global symbol "$subarray" requires explicit package name at lib/ModelSEED/MS/GapgenFormulation.pm line 125.
# Global symbol "$model" requires explicit package name at lib/ModelSEED/MS/GapgenFormulation.pm line 128.
# Global symbol "$model" requires explicit package name at lib/ModelSEED/MS/GapgenFormulation.pm line 132.
# Global symbol "$model" requires explicit package name at lib/ModelSEED/MS/GapgenFormulation.pm line 143.
# Global symbol "$ggsolution" requires explicit package name at lib/ModelSEED/MS/GapgenFormulation.pm line 156.
# Compilation failed in require at (eval 1332) line 2.
```

**Comment by cshenry** [comment]
I'm tied up in a panel review all day today, and I'd prefer to focus on the
tutorials otherwise. Honestly, these are minor errors... so if you can just
stick the requisite "my" in the proper place in the code, that would be
great.

**Comment by devoid** [comment]
`$subarray` is never populated. Should it be `$rxns` or `$row`? I'd think `$rxns` but you're using the `$j` index and not the `$m` index.

I'll fix the other stuff though.

**Comment by devoid** [comment]
FYI the `require.t` test suite can be really helpful at catching basic bugs.

**Comment by cshenry** [comment]
Yeah, that's cool. Thanks for pointing it out. I'll try and fix the
subarray problem tonight.

**Comment by devoid** [comment]
@cshenry The `$subarray` is still undefined in the master branch. Could you take a look and see what variable it should be replaced with?

**Comment by devoid** [comment]
Passes require test now.
