### ISSUE TITLE
updateLinks() does not seem to be updating compound_uuid in Reaction object

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/ModelSEED#131]
So my code is successful in merging the compounds, and I tested this extensively.

What the problem seems to be is that when the reactions themselves are added to the new biochemistry object, the compound_uuids themselves are not updated, and this is something that doesn't even happen <i>a posterior</i>, after saving the new biochemistry object.  Here's a simple example:

```
"reagents" : [
      {
         "isCofactor" : "0",
         "compound_uuid" : "E8126E18-1C6A-11E2-A7F1-78131FF72B0E",
         "compartment_uuid" : "5179DBA4-D6A0-11E1-830C-DE543D9902C7",
         "coefficient" : 2
      },
      {
         "isCofactor" : "0",
         "compound_uuid" : "E89115F6-1C6A-11E2-A7F1-78131FF72B0E",
         "compartment_uuid" : "5179DBA4-D6A0-11E1-830C-DE543D9902C7",
         "coefficient" : -1
      }
   ],

ms get bash-3.2$ ms get biochemistry/seaver/TestMerger/compounds/E8126E18-1C6A-11E2-A7F1-78131FF72B0E
hash- or arrayref expected (not a simple scalar, use allow_nonref to allow this) at /Users/seaver/Software/ModelSEED/lib/ModelSEED/App/mseed/Command/get.pm line 79.
```

So the compound I used in this example successfully matched a different compound, and its uuid was updated, so the uuid I list here actually disappears in the new biochemistry object, which is what I want, but its still there in the reagents list.

**Comment by cshenry** [comment]
So clearly update links isn't working. I'll try and fix it. Please don't write workarounds.

**Comment by cshenry** [comment]
Just checked in a fix for this. I _think_ it should resolve the problem.

**Comment by samseaver** [comment]
The "workaround" in question is necessary to actually match the compounds using aliases.  Merging the aliasSets at the end of the process would mean that the aliases themselves cannot be used to match and merge compounds which goes against the whole point of the mergeBiochemistry() function.  The original code would not work even if you were using 'searchname'.  This way, every time a compound gets added to the new biochemistry object, its alias is updated in real-time, and can then be used to check against the next compound in the loop.

**Comment by samseaver** [comment]
For the first time today, my code didn't throw an error.  Still double-checking, but thanks.

**Comment by cshenry** [comment]
I agree. I looked at the code, and it's good. Sorry to doubt.
Chris
