### ISSUE TITLE
Cloning an object

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/ModelSEED#133]
I have these cases where I basically need to copy a reaction, but change one of the compounds.  I can't really use updateLinks() in this case because I'm not changing the uuid of the compounds themselves.

Theres two similar ways I'm thinking I will have to do this:

1) is to write a 'clone' function where an object gets copied but its uuid itself gets reset, and I can then modify any of the attributes.

2) is to write a 'toHash' function for an object, where it returns all of its attributes in a hash that can then be passed into the Biochemistry::addReactionFromHash() function.

I'm doing 2) right now, but only for Reaction, and not for BaseObject but I thought I'd put this out there if there was a more appropriate way of doing this.

**Comment by cshenry** [comment]
I recommend the clone function. I can write it. Ill add it to base
object... as it happens, its incredibly easy to write... just serialize,
then deserialize, change uuid if there is one.

**Comment by devoid** [comment]
I think moose exports a function called "clone" so perhaps a different name? If you are modifying the reaction I hope you want to "replace" the unmodified one or "create" a new reaction in addition to the old one?

If its the first, add Reaction is not what you want. If its the second, you need a different uuid.

**Comment by samseaver** [comment]
Its the second, I do want to keep the old reaction.

In this particular example, the modification will entail the changing of a reagent's compartment_uuid, and thus the reaction itself will be a different reaction (I'll recompute other attributes such as deltaG etc.)

**Comment by cshenry** [comment]
I don't think the Moose clone operation is what we want. We have a clear mechanism for cloning only the data needed to fully describe the object, and that seems like what we want to use. I think using a Moose clone will bring with it unanticipated side effects.
Anyhow, I'm happy to write it right now. I'll make a branch and check it in... it really is very simple.
Chris

**Comment by devoid** [comment]
I agree completely. We may want to choose a different name to avoid any
confusion or possible conflicts.

**Comment by cshenry** [comment]
Clone object is done. Pull request is in. I even wrote and ran a test.

**Comment by samseaver** [comment]
Beautiful
