### ISSUE TITLE
dev-env.sh fails to run with current shebang (!bin/sh)

### ISSUE THREAD

**Issue by mattb112885** [ModelSEED/ModelSEED#136]
The dev-env.sh fails to run with /bin/sh (which is dash on Ubuntu machines) - it failed with the following error (but ran correctly when I ran with /bin/bash):

./dev-env.sh: 24: Bad substitution
./dev-env.sh: 1: [[: not found
./dev-env.sh: 1: [[: not found
./dev-env.sh: 1: [[: not found
./dev-env.sh: 1: [[: not found

It could be because /bin/sh doesn't define the BASH_SOURCE variable?

**Comment by devoid** [comment]
Switched script to use bash. I'm assuming everyone has this. Alternatively we could rewrite the script to use only basic sh scripting syntax, but I barely know bash syntax. Feel free to reopen if you want to take on that.
