### ISSUE TITLE
Command filename with hash picked up

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/ModelSEED#137]
This was completely random, but I tried to run a command before I had actually saved the file.  Emacs will sometimes write an auto-save file to disk, you rarely see it because it disappears as soon as you save the file you're working on.  For example, whilst working on transferrxn.pm, the file #transferrxn.pm# temporarily appeared.

When running my command (ms bio transferrxn) I got this error message:

```
search_paths: Can't open /Users/seaver/Software/ModelSEED/lib/ModelSEED/App/bio/Command/.#transferrxn.pm: No such file or directory at /System/Library/Perl/5.10.0/Module/Pluggable/Object.pm line 162.
```

Because I knew that emacs does this thing with auto-save files, I just went back and saved the file and I could run the program again without a problem.

The whole point of this post really is to say that this problem can come up for someone else, so the recognition of the command filenames needs to be more tightly regulated.

**Comment by devoid** [comment]
I guess I don't see this problem because vim saves it's temporary files as ".command.pm.swp" which are ignored. Since this is an issue with how `App::Cmd` finds commands, there's not much we can do.
