### ISSUE TITLE
Missing file from Build.PL

### ISSUE THREAD

**Issue by mattb112885** [ModelSEED/ModelSEED#139]
This one asked me to inform the author so here it is... Build.PL complains about a missing file when trying to run it:

WARNING: the following files are missing in your kit:
        lib/ModelSEED/MS/Environment.pm
Please inform the author.

**Comment by devoid** [comment]
Thanks, removed that file.
Fixed in 49fd5b2aa1d9c1aaba242d03dfa434bf3cb8b258.
