### ISSUE TITLE
ms list [object] -v does not work

### ISSUE THREAD

**Issue by mattb112885** [ModelSEED/ModelSEED#141]
Help for this command claims that there is a verbose option for listing:

$ ms list mapping -h
$ ms list [options] ref
        -v --verbose    Print out additional information about the object,
                        tab-delimited

But running it gives an error because the referenced function no longer exists (or is not in the same place any more). The same error occurs when you do it with biochemistries.

$ ms list mapping --verbose (or -v, it does the same thing)
Can't locate object method "verboseRules" via package "ModelSEED::App::mseed::Command::list"

Interestingly, the -v (or --verbose) doesn't crash if you just do this:

$ ms list -v

However, it doesn't do anything differently from omitting the -v.

**Comment by devoid** [comment]
Fixed. Remove -v option. See pull request for explanation.
