### ISSUE TITLE
Off-by-one in printdbfiles

### ISSUE THREAD

**Issue by mattb112885** [ModelSEED/ModelSEED#143]
The first line from the reaction table (generated by ms bio printdbfiles [my-biochemistry] on the default biochemistry) looks different from the rest - the abbreviation is cut off and the rest of the fields are shifted over by one.

First line of the output:

10000000        10000000        (1) cpd11463[c] <=> (1) cpd12036[c]     rxn05785        rxn05785        =       MI:C12/N7/O1/R-1|CI:3|HI:-21    =

The rest of the lines look like this:

rxn05784        10000000        10000000        (1) cpd11463[c] <=> (1) cpd12003[c]     rxn05784        rxn05784        =       MI:C12/N4/O1/R-1|CI:2|HI:-19    =

This only happens with the reaction table, not the compound table.

**Comment by devoid** [comment]
Fixed.

**Comment by mattb112885** [comment]
This isn't completely fixed - the column numbers are correct but still no abbreviation is printed for the first reaction.

**Comment by devoid** [comment]
Yea that one just doesn't have an abbreviation. Use the id column, which
should always be defined.
