### ISSUE TITLE
ms import model --list does not work

### ISSUE THREAD

**Issue by mattb112885** [ModelSEED/ModelSEED#147]
Default namespace should be 'model-seed' but running gives me this.

$ ms import model --list
Unknown source:

Setting the namespace automatically gives the same result:

$ ms import model --list --source 'model-seed'
Unknown source:

Also the -l vs --list is inconsistent across functions; ms import annotation requires -l (and does work correctly). Maybe this has something to do with the problem? (running the above command with -l just prints a syntax error and the help text)

$ ms import annotation -l
[Lists genomes]

**Comment by devoid** [comment]
Fixed now.
