### ISSUE TITLE
ms import biochemistry

### ISSUE THREAD

**Issue by pfrybar** [ModelSEED/ModelSEED#15]
I've started receiving this error on my main VM (running Arch Linux) when I run the ms import biochemistry command:

```
Can't call method "can" on an undefined value at /home/paul/local/lib/perl5/JSON/Any.pm line 573, <META> line 1.
```

I'm using a new local FileDB. Here is the output leading up to the error:

```
Will be saving to biochemistry/pfrybarger/main...
Fetching biochemistry from web...
Extracting...
Validating fetched biochemistry...
```

Tried upping memory from 1 GB to 2, but that didn't fix the problem. I'll try some print debugging to see if I can find the issue.

**Comment by pfrybar** [comment]
The error doesn't happen on Cygwin...

**Comment by pfrybar** [comment]
Performing a stack trace revealed that it's an issue with JSON::Any. It's having trouble decoding this string:

```
'{"aliases":{}}'
```

I changed FileDB (KeyValueStore) to use JSON::XS and the problem went away. Any objections to using this instead of JSON::Any?

**Comment by devoid** [comment]
No objections with JSON::XS over JSON::Any. It is concerning that we're
seeing that behavior though.

**Comment by pfrybar** [comment]
Yeah, I agree that it's concerning. If I get a chance I'll try and debug it a little more, maybe submit a bug report to the developer. But for now the easy fix is to just use JSON::XS

**Comment by cshenry** [comment]
Sounds fine to me.
