### ISSUE TITLE
Behaviour for missing compounds in reactions

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/ModelSEED#151]
There's been a couple of instances in the BioCyc databases where there is a reaction that contains reagents which don't exist in the list of compounds in the same database.  There's very few of these, but the default behaviour of the reaction loading code is to 'create' these compounds regardless.

1) Is this the behaviour we want? The alternative is to reject the reaction itself.  Allowing the reaction into the database is not going to add much because byt its nature (with no formula because its not in the database) the reaction becomes unbalanceable anyway.

2) If we do want to allow these to be included, again, the ID because the UUID, and not the ID used for the compound in the reaction.  I'm going to update the code so that its more readable when calling `-w equation` but let me know if you want to keep it as uuid.

**Comment by cshenry** [comment]
1.) I don't think it should be the default behavior, but it should be possible to activate this kind of behavior with a command line option

2.) I'm fine with this change.

**Comment by samseaver** [comment]
Done and tested
