### ISSUE TITLE
Global symbol requires explicit package name at ExchangeFormatFactory.pm line 92

### ISSUE THREAD

**Issue by mmundy42** [ModelSEED/ModelSEED#168]
The model runfba command gives this error:

$ model runfba my-model --html
Global symbol "$mapping" requires explicit package name at /home/mmundy/ModelSEED/ModelSEED/lib/ModelSEED/MS/Factories/ExchangeFormatFactory.pm line 92.
Compilation failed in require
 at /home/mmundy/ModelSEED/ModelSEED/lib/ModelSEED/App/model/Command/runfba.pm line 98.
    ModelSEED::App::model::Command::runfba::execute('ModelSEED::App::model::Command::runfba=HASH(0x289a980)', 'Getopt::Long::Descriptive::Opts::**OPT**::2=HASH(0x28c40f0)', 'ARRAY(0x23b6270)') called at /home/mmundy/local/lib/perl5/App/Cmd.pm line 243
    App::Cmd::execute_command('ModelSEED::App::model=HASH(0x27390e0)', 'ModelSEED::App::model::Command::runfba=HASH(0x289a980)', 'Getopt::Long::Descriptive::Opts::**OPT**::2=HASH(0x28c40f0)', 'my-model') called at /home/mmundy/local/lib/perl5/App/Cmd.pm line 171
    App::Cmd::run('ModelSEED::App::model') called at /home/mmundy/ModelSEED/ModelSEED/bin/model line 8
    main::**ANON**() called at /home/mmundy/local/lib/perl5/Try/Tiny.pm line 76
    eval {...} called at /home/mmundy/local/lib/perl5/Try/Tiny.pm line 67
    Try::Tiny::try('CODE(0x20e9788)', 'Try::Tiny::Catch=REF(0x2364a90)') called at /home/mmundy/ModelSEED/ModelSEED/bin/model line 16

The following patch seemed to fix the problem:

diff --git a/lib/ModelSEED/MS/Factories/ExchangeFormatFactory.pm b/lib/ModelSEED/MS/Factories/ExchangeFormatFactory.pm
index 76a3d72..e4e7f15 100644
--- a/lib/ModelSEED/MS/Factories/ExchangeFormatFactory.pm
+++ b/lib/ModelSEED/MS/Factories/ExchangeFormatFactory.pm
@@ -89,7 +89,7 @@ sub buildClassifier {
                $objData->{role_uuid} = $role->uuid();
                $cfRoleHash->{$row->[0]} = $classifier->add("classifierRoles",$objData);
        }
-       return ($classifier,$mapping);
-       return ($classifier,$args->{mapping});
  }

**Comment by linsalrob** [comment]
Confirmed that changing return ($classifier,$mapping); to return ($classifier,$args->{mapping});  fixes this problem.

**Comment by cshenry** [comment]
Fixed.
