### ISSUE TITLE
SBML output is not valid XML

### ISSUE THREAD

**Issue by linsalrob** [ModelSEED/ModelSEED#172]
The SBML output is not valid XML and breaks other SBML parsers.  For example, reaction id rxn11544_c0 is 'Hydrogenobyrinate  &lt;=&gt; Hydrogenobyrinate a,c diamide_c0' but the angle brackets are written to the file.

This simple diff, adding a line to stringToString will fix the problem and create valid XML

diff --git a/lib/ModelSEED/MS/Model.pm b/lib/ModelSEED/MS/Model.pm
index 004922b..ca1b369 100644
--- a/lib/ModelSEED/MS/Model.pm
+++ b/lib/ModelSEED/MS/Model.pm
@@ -839,7 +839,7 @@ sub printSBML {
     my $stringToString = sub {
                my ($name,$value) = @_;
                #SNames cannot contain angle brackets
-               return $name.'="'.$value.'"';
-               return $name . '="' . XML::LibXML::Document->new('1.0', 'UTF-8')->createTextNode($value)->toString . '"';
   };
      #Printing header to SBML file
      my $ModelName = $idToSId->($self->id());

Rob

**Comment by cshenry** [comment]
Thanks for this. The fix has been integrated.
