### ISSUE TITLE
Use of implicit split to @_ is deprecated at lib/ModelSEED/MS/Factories/ExchangeFormatFactory.pm line 70.

### ISSUE THREAD

**Issue by linsalrob** [ModelSEED/ModelSEED#173]
Minor fix to split to an arrayref not a variable, that is giving the deprecated @_ split warning in ExchangeFormatFactory.pm

diff --git a/lib/ModelSEED/MS/Factories/ExchangeFormatFactory.pm b/lib/ModelSEED
index 76a3d72..7b21fc3 100644
--- a/lib/ModelSEED/MS/Factories/ExchangeFormatFactory.pm
+++ b/lib/ModelSEED/MS/Factories/ExchangeFormatFactory.pm
@@ -67,7 +67,7 @@ sub buildClassifier {
        }
        my $cfRoleHash = {};
        for (my $i=2;$i < @{$data}; $i++) {
-               my $row = split(/\t/,$data->[$i]);
-               my $row = [split(/\t/,$data->[$i])];
              my $objData = {
                      classifications => [],
                      classification_uuids => [],

**Comment by cshenry** [comment]
Fixed.
