### ISSUE TITLE
Tutorial/Snippets on how to integrate MS code into other scripts

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/ModelSEED#22]
I frequently wrote scripts for specific circumstances that used the MS code, to the point at which I kept my own little library that frequently called the same Model objects and ran the same functions found in FIGMODEL.pm etc.

As clean as the command line interface as worked for me so far, I know I'll have to expand functionality from time to time, or even write test scripts for new functions that can then be migrated into MS code.

So I need some examples of what I can do, my first question is, how can I load/initialize a biochemistry object from the store in a script?

**Comment by devoid** [comment]
Hmmm....

Within a Perl script I don't envision the command line environment will help you much...perhaps that is a flaw with how we designed it. However, it's relatively easy to call the underlying libraries to retrieve biochemistry, mapping, annotation and model objects---the four "provenance" objects we currently have:

```
use ModelSEED::Store;
use ModelSEED::Auth::Factory;
my $auth = ModelSEED::Auth::Factory->new->from_config;
# create an "authorization object" using the config file typically located at
# $HOME/.modelseed
my $store = ModelSEED::Store->new(auth => $auth);
# create a store access object ( where the database is configured with the
# same config file as above
my $biochem = $store->get_object("biochemistry/seaver/foo");
# where "biochemistry/seaver/foo" is the saved name of a biochemistry
# object that you added to your data-store
my $compounds = $biochem->compounds();
# array ref of ModelSEED::MS::Compound objects...
my $reactions = $biochem->reactions();
# array ref of ModelSEED::MS::Reaction objects...
```

Let me know if that doesn't make sense to you. Or if you have suggestions on making the CLI more scriptable...

**Comment by devoid** [comment]
Now I'm thinking I left a bit out...

For tutorial info, we need to figure out what to "open up" to outside usage and what to leave closed. I don't know what parts of the codebase we can commit to supporting in scripts written by non Argonne folks at the moment...

For the `ModelSEED::Auth` stuff... some context:

All storage operations in the `ModelSEED::Store` class come with a user context. That context is encapsulated in a `ModelSEED::Auth` object. There are two current objects that implement this base-class:
- `ModelSEED::Auth::Basic` - Username + Password authentication
- `ModelSEED::Auth::Public` - A class for non-authorized usage, e.g. read-only on all / most objects.

Then there's a class called `ModelSEED::Auth::Factory` which constructs an object from, among other things, the JSON config file defined by `ModelSEED::Configuration` which is typically located at `$HOME/.modelseed`

I hope that further clarifies things...

**Comment by cshenry** [comment]
Personally Sam, I believe you'll find the new system is WAY better for this than the old system was. This is because 99% of the meaningful code is in the ModelSEED::MS objects, and retrieving these objects from the store is incredibly simple. 90% of the code in the CLI really is just the code for interfacing with the user, as it should be. I agree we need such a tutorial though. We should write one in the wiki that builds on what Scott has written above.

**Comment by samseaver** [comment]
I don't see any need in making the CLI more scriptable, but I do personally have a need to process things in bulk, and would therefore want to avoid re-running a command through a shell.

I can see how things will be more straightforward with the new MS objects, I just needed to know the correct way to go about initializing them before I can access them.

Scott's little snippet works just fine.

Following up, I did also have a question about the ModelSEED::Store, I can see that I can pass in a ModelSEED::Database object.  I was wondering if it would be possible to create a ModelSEED::Database object that can actually connect with a database that I have on biologin-4.  In this way, I can write test scripts with a local test database/provenance, and then once I'm sure it would work, instead of logging into biologin-4, and then copying the scripts(or pulling them as you will) I can simply swap database objects.

But I understand that what I'm asking means having a model seed configuration file ready at the remote location.

**Comment by devoid** [comment]
The short answer is yes, you can construct a ModelSEED::Database object and
pass it into ModelSEED::Store, which avoids having to use the config file.
However the mongodb set up within the bio environment does not accept
connections from outside the domain, so you wouldn't be able to connect to
it. I've had plans to implement a ModelSEED::Database that works against an
API that we would expose. Implementing that alone shouldn't take more than
a few days, but 1) I need to budget time for it and 2) there are
complexities involved in "getting it right". By that I mean implementing
sensible caching on the client side to avoid making a lot of needless
round-trips.

**Comment by samseaver** [comment]
I don't need you to budget time to implement that now, we can make it a future feature.

You do however bring up something I hadn't considered.  I did successfully follow the tutorial on importing the biochemistry on bio too, so I now have a local copy of the database there.  But I will also need to copy/update what I implement in the local biochemistry into the public database at some point, on the MongoDB at bio, but this probably needs another discussion of its own in a week or two once I make headway.

**Comment by mdejongh** [comment]
I am trying to work with the MS objects now too, and will have some of the same issues that Sam is raising. For now, I have the following question:

How do I access the ModelSEED aliases (e.g., rxn00001 and cpd00001) and the KEGG aliases (e.g., C00001, R00001)?

My guess is that they are in the MongoDB store ... so what are the arguments to "ms stores add" that I need to access the MongoDB store?

**Comment by cshenry** [comment]
Well, if you run ms list ...../reactions -w id, you'll print the rxn IDs in addition to the uuid.
I could add a function to BaseObject called "allAliasesString" that returns a list of all aliases (e.g. KEGG:C00001|Name:Water;H2O|ModelSEED:cpd00001). This could then be used to print all aliases in the ms list command:

ms list .../reactions -w allAliasesString

Does that make sense? Will that meet your needs matt?

**Comment by mdejongh** [comment]
I'm trying to get it programmatically. I figured out how, but it may not be the most elegant way. The following code builds hashes from reaction_uuid to alias for three different sets of aliases; comments welcome:

my $biochemistry = $model->biochemistry();

my %aliasHash;
foreach my $aliasSet (@{$biochemistry->aliasSets()}) {
    next unless $aliasSet->name() eq "ModelSEED" || $aliasSet->name() eq "KEGG" || $aliasSet->name() eq "Enzyme Class";
    my $aliases = $aliasSet->aliases();
    foreach my $alias (keys %$aliases) {
    foreach my $uuid (@{$aliases->{$alias}}) {
            push @{$aliasHash{$aliasSet->name()}->{$uuid}}, $alias;
    }
    }
}

**Comment by devoid** [comment]
So the documentation is in a sorry shape right now, but here's what you're looking for:

Assume that your biochemistry object has it's "defaultNameSpace" attribute (a string) set to "ModelSEED". If that's the case:

```
my $bio    = $model->biochemistry();
my $cpds = $bio->compounds();
my $cpd   = $cpds->[0];
print $cpd->id; # prints "cpd00001"
```

If your defaultNameSpace is something else, it will try to lookup the compound's name within that alias set. The default is to print the UUID if it is unable to find an alias. Where there are multiple aliases for a given compound, we return the first.

To lookup an arbitrary alias for a compound:

```
my $kegg = $cpd->getAlias("KEGG");
print $kegg; # prints "C01234"
my $all_kegg = $cpd->getAliases("KEGG");
# array ref of all KEGG aliases for compound.
```

**Comment by cshenry** [comment]
This seems like a reasonable approach to take to make such a hash. One not about your code though, and this comment should be added to a special wiki on coding in the Model SEED.

The functions that retrieve arrays of subobject, such as biochemistry->compounds, or biochemistry->aliasSets which you use below, are very expensive to call. So you want to take great care that you call them only once.
So your code will work faster if it's written like so:

``` perl
my $biochemistry = $model->biochemistry();
my %aliasHash;
my $aliasSets = $biochemistry->aliasSets();
foreach my $aliasSet (@{$aliasSets}) {
    next unless $aliasSet->name() eq "ModelSEED" || $aliasSet->name() eq "KEGG" || $aliasSet->name() eq "Enzyme Class";
    my $aliases = $aliasSet->aliases();
    foreach my $alias (keys %$aliases) {
        foreach my $uuid (@{$aliases->{$alias}}) {
            push @{$aliasHash{$aliasSet->name()}->{$uuid}}, $alias;
        }
}
```

But FYI, all objects have the following alias function, which are implemented in BaseObject.pm:

``` perl
sub getAlias {
    ...
}

sub getAliases {
    ...
}
```

The first function returns the first alias in the specified set:

``` perl
my $ModelSEEDID = $compound->getAlias("ModelSEED");
```

The second function returns the array of aliases:

``` perl
my $names = $compound->getAliases("name");
print $name->[0];
```

Also note the following functions are available for any provenance object, or any object that has aliasSets as children:

``` perl
sub addAlias {
    ...
}

sub getObjectByAlias {
    ....
}

sub getObjectsByAlias {
    ...
}
```

The first functions adds a new alias to the provenance object.
The second function gets an object by it's alias.
The third function gets a set of objects by their alias.

**Comment by cshenry** [comment]
Scott,

Can you take the response you just wrote in this thread and the response I just wrote and copy them into a wiki page on git hub called "Aliases in the Model SEED"?
Don't worry about making it look nice if you're busy... Just get the content in there. I want to do this before we forget.

Chris

**Comment by pfrybar** [comment]
The first call to get the sub-objects array (i.e. $biochem->compounds) initializes each sub-object, so subsequent calls should run relatively fast...

**Comment by cshenry** [comment]
Nope. It's still slow.... because the system initializes a new array, and fills it in with subobjects EVERY time, even if it only creates the subobjects the first time.
Doesn't sounds like much, but if someone really abuses the subobject array functions, it kills you.

You know, this is completely avoidable if you code with the right style... I mean, I completely agree with Scott that's it's bad, so we should fix it.... but there's a question of whether there exists a solution that doesn't add massive complexity or introduce new problems of its own. What I'm really saying is... this problem is a small one and one we can live with if we have to if there's no good work around. But I'm game for looking for a simple fix.

**Comment by pfrybar** [comment]
Also...

```
foreach my $aliasSet (@{$biochemistry->aliasSets()})
```

and

```
my $aliasSets = $biochemistry->aliasSets();
foreach my $aliasSet (@{$aliasSets})
```

will perform exactly the same.

**Comment by pfrybar** [comment]
The reason I coded it to return a new array every time is so that the resulting array is mutable. My thought was that someone might want to edit the array, and if we store and return an array reference, then he/she may unintentionally alter the internal data.

If you think we should do it this way, I can make the change, but we should think about what it would mean to edit this sub-object array... if we add new sub-objects to it, or change the order, should these changes be reflected once we save the provenance object?

**Comment by devoid** [comment]
Here are the example use cases. I had to comment out Case 1 and 2 because the would not complete within 7 minutes. The last three cases run in the same time-period.

``` perl
#!/usr/bin/perl 
use common::sense;
use ModelSEED::Store;
use ModelSEED::Auth::Factory;
use Time::HiRes qw( time );

my $t;
sub delta { 
    my $m = shift;
    my $n = time;
    printf("%s : %0.3f seconds\n", ($m, ($n-$t)));
    $t = $n;
}
my $auth  = ModelSEED::Auth::Factory->new->from_config;
my $store = ModelSEED::Store->new(auth => $auth);

my $bio   = $store->get_object("biochemistry/sdevoid/web");
# prefetch once before everything:
$bio->compounds();
$t = time;
=cut
# Case 1 - call compounds() twice inside loop
{
    for(my $i=0; $i<@{$bio->compounds()}; $i++) {
        my $cpd = $bio->compounds()->[$i];
    }
    delta("Case 1");
}
# Case 2 - call compounds() once inside loop
{
    my $size = scalar(@{$bio->compounds()}); 
    for(my $i=0; $i<$size; $i++) {
        my $cpd = $bio->compounds()->[$i];
    }
    delta("Case 2");
}
=cut
# Case 3 - call compounds with foreach
{
    foreach my $cpd (@{$bio->compounds()}) {
        next;
    }
    delta("Case 3");
}
# Case 4 - call compounds once (Version of Case 2)
{
    my $compounds = $bio->compounds();
    my $size = @$compounds;
    for(my $i=0; $i<$size; $i++) {
        my $cpd = $compounds->[$i];
        next;
    }
    delta("Case 4");
}
# Case 5 - call compounds once (Version of Case 3)
{
    my $compounds = $bio->compounds();
    foreach my $cpd (@$compounds) {
        next;
    }
    delta("Case 5");
}
```

```
Case 3 : 0.021 seconds
Case 4 : 0.027 seconds
Case 5 : 0.024 seconds
```

**Comment by pfrybar** [comment]
Sorry, I don't mean to spam this thread... but I wanted to post benchmarks:

**$biochem->compounds** takes 2.8 seconds the first time, and 0.02 seconds after

**Comment by cshenry** [comment]
Thanks Scott and Paul. Again, I'm personally okay with the current implementation, especially given Paul's comment about the arrays being mutable.
I agree with this. I think it's a fair concern, and a very good reason to leave the system the way it is.

I also appreciate you guys clarifying the foreach command. I was uncertain how that command works in perl, so it's good to know it doesn't have a problem calling the array directly (must only call it once).
Still, as Scott demonstrates below, I think it's a good idea to emphasize caution to developers using those subobject calls, as obviously the way you use them has a massive impact on performance.

**Comment by mdejongh** [comment]
Thanks for the clarifications. I will try the getAlias and getAliases functions. I think that documenting and providing code snippets for canonical ways of getting data (e.g., the ModelSEED Cookbook) is the best way to help developers do things right.
