### ISSUE TITLE
Functionality of an MS Object

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/ModelSEED#24]
Some of the functionality for an object, such as MS::Compound is found in MS::DB::Compound and MS::BaseObject etc.  For any given MS Object, could I get a list of places to look for functions that apply to that object?  I know as I get into this, it'll come to me naturally.

**Comment by mdejongh** [comment]
I think the place to look is MS/Metadata/Definitions.pm

On Fri, Aug 24, 2012 at 5:16 PM, samseaver notifications@github.com wrote:

> Some of the functionality for an object, such as MS::Compound is found in
> MS::DB::Compound and MS::BaseObject etc. For any given MS Object, could I
> get a list of places to look for functions that apply to that object? I
> know as I get into this, it'll come to me naturally.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ModelSEED/ModelSEED/issues/24.

## 

Matt DeJongh, Ph.D.
Computer Science Department
Hope College, Holland, MI 49423
(616) 395-7429

**Comment by samseaver** [comment]
You're right, following up on that, the appropriate wiki page is:

https://github.com/ModelSEED/ModelSEED/wiki/Object-Definitions

**Comment by devoid** [comment]
So the class hierarchy looks like this:
- ModelSEED::MS::Compound - top level object with class-specific functions, unsaved attributes
- ModelSEED::MS::DB::Compound - automatically generated class with saved attributes
- ModelSEED::MS::BaseObject - basic class functions that all objects have

In addition, some objects (Biochemistry, Mapping, etc.) inherit from ModelSEED::MS::IndexedObject which defines some functions for looking up sub-objects by attributes. Take a look at the Definitions.pm file to see which objects are "indexed" and which ones are not.

**Comment by mdejongh** [comment]
Thanks Scott. By the way, it seems that this tutorial should be in
ModelSEED/ModelSEED, rather than Model-SEED-Core:

https://github.com/ModelSEED/Model-SEED-core/wiki/Tutorial:-Getting-Started

On Fri, Aug 24, 2012 at 5:44 PM, Scott Devoid notifications@github.comwrote:

> So the class hierarchy looks like this:
> - ModelSEED::MS::Compound - top level object with class-specific
>   functions, unsaved attributes
> - ModelSEED::MS::DB::Compound - automatically generated class with
>   saved attributes
> - ModelSEED::MS::BaseObject - basic class functions that all objects
>   have
> 
> In addition, some objects (Biochemistry, Mapping, etc.) inherit from
> ModelSEED::MS::IndexedObject which defines some functions for looking up
> sub-objects by attributes. Take a look at the Definitions.pm file to see
> which objects are "indexed" and which ones are not.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ModelSEED/ModelSEED/issues/24#issuecomment-8015720.

## 

Matt DeJongh, Ph.D.
Computer Science Department
Hope College, Holland, MI 49423
(616) 395-7429

**Comment by devoid** [comment]
Sorry, that didn't get copied over when we moved. It's fixed now.

**Comment by cshenry** [comment]
ModelSEED::MS::DB::..... Contains all attributes and links for the objects, but this is limited only to data that is stored in the database. Note, these objects are not to be modified manually. They are automatically generated by the ModelSEED/scripts/ObjectBuilder.pl script based on the content of the ModelSEED/lib/ModelSEED/MS/Metadata/definitions.pm. So if you want to alter data stored for an object in the database, you should alter definitions.pm and rerun ObjectBuilder.pl.

Now, there is also the ModelSEED::MS::.... Files. These files contain computed attributes, as well as functions for objects. If you look at the db and ms files, you'll see all the specific functions for each object.

All objects extend the ModelSEED::MS::BaseObject class, so look in there for generic functions. Finally, any object with indexable subobjects (e.g. Biochemistry, Model) also extends the ModelSEED::MS::IndexedObject class.
