### ISSUE TITLE
Remove modelanalysis from Model Object

### ISSUE THREAD

**Issue by mdejongh** [ModelSEED/ModelSEED#33]
models have a "modelanalysis" attribute that links to a ModelAnalysis object .. but where is the object definition? Is there where the Flux Variability Analysis results will be stored?

**Comment by cshenry** [comment]
At one point, we were putting FBA and gapfilling formulations in there. Now those objects are stored directly in the model. So it's:

Model -> FBAFormulation -> FBAResults

FBAResults is where FVA is stored.

**Comment by devoid** [comment]
I removed ModelAnalysis in pull request #44.

**Comment by cshenry** [comment]
This is done now.
