### ISSUE TITLE
AliasSet clarification

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/ModelSEED#35]
Can you confirm for me what the different fields are for in AliasSet, they may be self-evident but put together there's room for ambiguity:

name
source
attribute
class

**Comment by cshenry** [comment]
name: name of the alias set (e.g. ModelSEED, name, KEGG, SamFlag
source: some sort of indicator of where the aliases came from (e.g. KEGG, ModelSEED, KBase, Sam?)
attribute: name of the subobject attribute that the aliases are associated with (e.g. compounds, reactions)
class: object class that the aliases are associated with (e.g. Compound, Reaction)

I suppose "class" and "source" are a bit unnecessary, but I didn't mind the redundancy considering we won't have _that_ many different alias sets.
