### ISSUE TITLE
Creating/Adding new subobjects

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/ModelSEED#36]
At the start of https://github.com/ModelSEED/ModelSEED/wiki/Object-Definitions is a description explaining how to create objects, and indicates how to change fields within an object, but nowhere can I find a description on how to associate objects.

I can see the 'add' functions in BaseObject and IndexedObject classes but I take it that the function is used thus:

```
$biochem->add("AliasSet",$new_aliasSet);
```

**Comment by cshenry** [comment]
Yes, to add a subobject to an indexed object, you use the "add" command. You can either add an actual object, or the hash ref you would feed into the object constructer. Like so:

$biochem->add("aliasSets",{
    name => "ModelSEED",
    source => "ModelSEED",
    class => "Compound",
    attribute => "compounds"
});
- or -

my $aliasSet = ModelSEED::MS::AliasSet({
    name => "ModelSEED",
    source => "ModelSEED",
    class => "Compound",
    attribute => "compounds"
});
$biochem->add("aliasSets",$aliasSet );

NOTE: on the add command, we use the subobject attribute name in biochemistry ("aliasSets"), NOT the subobject class ("AliasSet"). While this may be confusing, in general we use the attribute names instead of the class because it may be possible we will someday have a provenance objects with two different sets of subobjects that both have the same Class.

**Comment by samseaver** [comment]
On your last note, there's potential for a lot of confusion here, especially, as I realize, the Object Definitions page in the wiki doesn't necessarily state what the attribute string is that can be used to represent each object.

Thinking about this, I take it that the attributes of a biochemistry object summarize what can be directly added to a biochemistry object, or are, in other words, the string that would be used for the function to retrieve/access the subobjects (ie $biochem->aliasSets()) and the same goes for other subobjects (ie $compound->structures()) but this needs to be clearer in the documentation.

**Comment by cshenry** [comment]
I'm honestly not sure what we can do about this. We can't spend all our time writing documentation, and my goal really isn't to enable the whole world to "code" within Model SEED... just for people to be able to use the system.

**Comment by devoid** [comment]
We need to do two things:
1. Have reasonably stable object structures that we expose (JSON) to the public over APIs.
2. Have a reasonable perl API that doesn't break every time we change the underlying data structure.

These two are complimentary; having spent a while with the MS objects now I think the tricks are:
1. Small objects are easier to "fake" the structure than large ones. So breaking up the big provenance objects while keeping the provenance features would be really good. (no ideas on how to do this now)
2. Object "references" needs a stronger representation in the (JSON) layer.
3. Data updates are exposed over functions, not through perl refs.

~ Scott

**Comment by samseaver** [comment]
All I need is a list of the attribute strings that correspond with each class.  I can guess most of them, but I'm not sure if using the wrong string would break something.

**Comment by cshenry** [comment]
Perfect. We already have that in the object definitions table:
https://github.com/ModelSEED/ModelSEED/wiki/Object-Definitions
Look at Biochemistry. It clearly says "aliasSets, an array of AliasSet."

**Comment by samseaver** [comment]
Ah, goody gumdrops!

**Comment by devoid** [comment]
Closing; I think the question was answered.
