### ISSUE TITLE
Deleting an object from store

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/ModelSEED#37]
I just ran: 

```
ms bio create help
```

and I now have a biochemistry called 'help'.

The closest thing I can find to a delete/remove function is Store::delete_data() is this what I should use to remove a biochemistry?

**Comment by devoid** [comment]
It's not implemented yet. I'm not sure how we want to handle this as our
system expects objects to stay around forever.

~ Scott

**Comment by pfrybar** [comment]
Right, one of the things we need to think about more before exposing the functionality. In the meantime I can show you how to delete it via a script. You're using the FileDB correct?

**Comment by samseaver** [comment]
I don't actually know, seeing the import/install process was so smooth, I'm not sure of the underlying workings.  I'm assuming the default is FileDB, you can email me the fix, which I take it is more of a direct SQL query.

**Comment by samseaver** [comment]
Given that you expect objects to be permanent to some extent, a second affirmation would be a good idea for any 'create' command that reads something like:

```
You are about to create a new biochemistry object with the name 'help'. Proceed? Y/N
```

**Comment by devoid** [comment]
The names you give objects are changeable since that's just a pointer to
the UUID associated with the object. The object itself is immutable, so
deleting it is problematic. We could delete the alias, so the user would
"think" it's gone... but that doesn't address the "garbage-collection" that
needs to happen if a user actually wants to save on disc space.

~ Scott

**Comment by samseaver** [comment]
I'm just about to test the loading of several tens of thousands compound structures, if I were to "delete" any of these, would my biochemistry still be slower to load?

**Comment by devoid** [comment]
Yes, each time you save you create a new document. Smaller documents will
load faster.
With regard to compound structures, I think we ought to pull them out of
the Biochemistry and put them into a CompoundStructures provenance object
that's linked to a biochemistry?

~ Scott

**Comment by samseaver** [comment]
Chris was saying yesterday that we can have a separate provenance for compoundStructures, but I'll still need InChI strings in an AliasSet for a biochemistry merge.  As long as I can delete then save a reduced biochemistry object, I'm good.

The idea of rogue disassociated objects building up within the database can be a cause for concern though.

**Comment by cshenry** [comment]
I would suggest md5 or sha the Inchi keys you put in the aliases... Just to keep them shorter.
Chris

**Comment by samseaver** [comment]
A very simple fix, if one hasn't done too much with the biochemistry, is to delete the store itself.  You can print out the very objects they wish to keep, as backup, and then run

```
ms stores rm <store>
ms stores add <store> --type file
```

To be sure, this does mean that you're deleting _everything_ in the store, but if you have saved objects, this is surprisingly an easy way of starting over.

**Comment by devoid** [comment]
I think issue #71 will address this in the general case. We probably still need a way to "remove" an alias... so I've created another issue #78 which addresses the other half of this problem.
