### ISSUE TITLE
Repetitive depreciation warning 

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/ModelSEED#38]
I'm getting this message every time I run MS now:

Use of implicit split to @_ is deprecated at /Users/seaver/Software/ModelSEED/lib/ModelSEED/App/Helpers.pm line 56.

**Comment by devoid** [comment]
What SHA1 of the code are you using? My line 56 doesn't have this problem:
(1f705e9437ca8e96525c101b0fe6653cd640a94d)

``` perl
sub process_ref_string {
    my ($self, $refString, $type, $username) = @_; 
    my $count = split(/\//, $refString); # line 56
    ...
```

**Comment by samseaver** [comment]
Oh that's weird, it tells me that Helpers.pm is "outside repository".

I used @pfrybar's install script, the git commands in it are:

```
git clone https://github.com/ModelSEED/ModelSEED.git 1>$OUT 2>&1; check_error
git clone https://github.com/ModelSEED/MFAToolkit.git 1>$OUT 2>&1; check_error 1>$OUT 2>&1; check_error
```

Have I missed something?

**Comment by samseaver** [comment]
Oh forget it, I was in a different repository when I tried to check, silly me.  The SHA1 for Helpers.pm is: b45919ededf6dd4d698bb44cf888cc738e063c10

**Comment by devoid** [comment]
Are you getting the error with that  version of the code?

**Comment by samseaver** [comment]
The SHA1 I posted for App/Helpers.pm was specifically for that file, if I do a git log at the root of the code tree, I get a more recent SHA1, which SHA1 do you need?  I just did a git pull to get Paul's most recent merges and I still get the error.

It might not be the code however, it just occurred to me that there might be something in a local file that calls this to be thrown?
