### ISSUE TITLE
Error warnings

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/ModelSEED#40]
I just ran 

```
ms list biochemistry/Current_MS_Biochem
```

and got:

```
Invalid Reference at /Users/seaver/Software/ModelSEED/lib/ModelSEED/Reference.pm line 249.
```

I understood the error straight away, as I didn't have my username in the biochemistry reference path but the error reported is not one that can be understood intuitively, and two, I was wondering what the system is for reporting errors to the user.  I can see that there is an ms-error, but funnily enough:

```
Couldn't open dir  at /Users/seaver/Software/ModelSEED/lib/ModelSEED/App/mseed/Command/error.pm line 55.
```

**Comment by devoid** [comment]
There's a way to report it over the CLI in ModelSEED::Exceptions
I'll get on implementing it. I'm thinking ms-error may be dead; it's not a exceptionally ;) good way to do things.

~ Scott

**Comment by devoid** [comment]
There are still some bugs in `ModelSEED::Reference` but this is now returning a fairly good error message:

```
Bad reference: 

References take the form of:

    biochemistry/username/string or
    biochemistry/E29318E0-C209-11E1-9982-998743BA47CD

Where "biochemistry" is the type, "username" is probably
your username; run: "ms whoami" to find out. "string" can
be whatever you want but cannot contain slashes.

In the second case, pass in a specific object UUID.
```
