### ISSUE TITLE
Behavior of the list/get commands

### ISSUE THREAD

**Issue by cshenry** [ModelSEED/ModelSEED#5]
It seems like the following command should work to print a list of all the aliasSets in a biochemistry:

ms list biochemistry/chenry/main/aliasSets | ms get

However, this command just results in a printing of the usage for the get command:

Error: Must provide at least one reference
Usage: ms <command>

ms get [ref] [- references] [options]
    -f --file     Print output to a file
    -p --pretty   Pretty-print JSON

My guess is we need to alter the get command to accept STDIN as input.

**Comment by devoid** [comment]
This works, but `ms get` must be passed an argument indicating that you should read from STDIN, the `-` character.
