### ISSUE TITLE
ms stores rm not actually removing biochemistry

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/ModelSEED#71]
I thought this used to work, but I'm no longer certain.   The problem with this:

```
bash-3.2$ ms stores rm local
bash-3.2$ ms stores add local --type file
bash-3.2$ ms list biochemistry
biochemistry/seaver/Current_MS_Biochem
biochemistry/seaver/EcoCyc
biochemistry/seaver/Old_MS_Biochem
```

is that I assume that when I re-create the store, it'll be completely empty.

Additionally, when I run:

```
bash-3.2$ ms save biochemistry/seaver/Old_MS_Biochem < /Users/seaver/Documents/Projects/MS_Biochemistry/biochem.dat
Upgrading biochemistry from v1 to v2!
bash-3.2$ ms list biochemistry/seaver/Old_MS_Biochem
compounds                       (29288)
aliasSets                       (158)
cues                            (324)
reactions                       (22859)
compartments                    (13)
media                           (525)
ancestor_uuids                  (1)
```

I can only assume that the ms save function actually overwrote the biochemistry object?

**Comment by pfrybar** [comment]
Currently the FileDB does not know when a database instance is removed (it also doesn't know when one is added). So when you try to remove the store, the files (~/.modelseed_filedb/*) don't get removed.

I think the best way to deal with this would be to add new methods to the Database interface (Database.pm) for add_database and remove_database, which get called by the stores CLI.

@devoid any thoughts?
