### ISSUE TITLE
Bizarro JSON::PP and JSON::XS 

### ISSUE THREAD

**Issue by devoid** [ModelSEED/ModelSEED#88]
I did a `perl -d:NYTProf model runfba my_model` today because it was feeling sluggish. Turns out I'm using `JSON::PP` instead of `JSON::XS`, which accounts for a lot of the slowness...

So I stuck some

``` perl
warn JSON->new->backend
```

statements in the code and ran:

``` bash
$ ms list biochemistry/sdevoid/main
JSON::XS at lib/ModelSEED/App/Helpers.pm line 212.
JSON::XS at lib/ModelSEED/Database/MongoDBSimple.pm line 577.

$ ms runfba my_model
JSON::PP at /lib/ModelSEED/App/Helpers.pm line 212.
JSON::PP at /lib/ModelSEED/Database/MongoDBSimple.pm line 577.
```

wth? The `JSON` and `JSON::Any` modules both try to use `JSON::XS` above `JSON::PP`... so why are we having this issue? I'm almost inclined to switch completely to `JSON::XS`.

**Comment by pfrybar** [comment]
I remember seeing that odd behavior before... I say let's just switch
completely to JSON::XS.

**Comment by cshenry** [comment]
Agreed.

**Comment by samseaver** [comment]
The JSON::XS page describes some fallback behaviour concerning JSON::PP:

```
http://search.cpan.org/~mlehmann/JSON-XS-2.33/XS.pm
```

Perhaps this is what happened, in some way.

**Comment by pfrybar** [comment]
We decided to use JSON::XS only, code changes in pull request #89
